version: '3' #docker version
services:
  www:
    image: php:apache
    volumes:
      - "./:/var/www/html" #dincronicar project dir con el contendor web dir
    ports:
      - 80:80
      - 443:443 
    depends_on:
      - db
  db:
      image: mysql:latest
      environment:
        - MYSQL_DATABASE=php_docker
        - MYSQL_USER=php_docker
        - MYSQL_PASSWORD=password 
        - MYSQL_ALLOW_EMPTY_PASSWORD=1 #equivalente a True
      volumes:
        - "./db:/docker-entrypoint-initdb.d" #sincronizar arcchivos sql con el contenedor
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db
